import { ReactNode } from "react";
import styled from "styled-components";
import Head from "next/head";
import Link from "next/link";
import { Header } from "./Header";

type LayoutProps = {
  children: ReactNode;
  home?: boolean;
};

const Screen = styled.div`
  // fill viewport
  width: 100vw;
  height: 100vh;
  // centre children
  display: flex;
  justify-content: center;
  background: black;
`;

const Content = styled.div`
  display: flex;
  flex-direction: column;
`;

const BackToHome = styled.div`
  // margin: 3rem 0 0;
`;

export const name = "Clifford Fatknax Presents...";
export const siteTitle = "Next.js Sample Website";

export default function Layout({ children, home }: LayoutProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Screen>
        <Content>
          <Header>
            <p>NextJS PWA Sandbox</p>
          </Header>
          {children}
          {/* TODO: put home link in bottom and top menus */}
          {!home && (
            <BackToHome>
              <Link href="/">← Back to home</Link>
            </BackToHome>
          )}
        </Content>
      </Screen>
    </>
  );
}
{
  /* <Header>
        {home ? (
          <>
            <Image
              priority
              src="/images/cliff.jpg"
              className={utilStyles.borderCircle}
              height={144}
              width={144}
              alt=""
            />
            <h1 className={utilStyles.heading2Xl}>{name}</h1>
          </>
        ) : (
          <>
            <Link href="/">
              <Image
                priority
                src="/images/cliff.jpg"
                className={utilStyles.borderCircle}
                height={108}
                width={108}
                alt=""
              />
            </Link>
            <h2 className={utilStyles.headingLg}>
              <Link href="/" className={utilStyles.colorInherit}>
                {name}
              </Link>
            </h2>
          </>
        )}
      </Header> */
}
{
  /* <main>{children}</main> */
}
