import Head from "next/head";
import Link from "next/link";
import { Inter } from "next/font/google";
import Layout from "@/components/layout";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* 
      TODO: get responsive mobile styling ideas from other old project
      TODO: use 'react-responsive' again? 
      */}
      <Layout home>
        <h1>Examples</h1>
        <h2>Using Pages Router</h2>
        <p>
          <Link href="card-deck/">Card Deck</Link>
        </p>
        <p>
          <Link href="pokemon/infinite-scroll/">
            Pokemon Feed (using infinite scroll)
          </Link>
        </p>
        <p>
          <Link href="pokemon/pagination/">Pages of Pokemons</Link>
        </p>
        <p>
          <Link href="posts/">Posts retrieved from standalone Payload CMS</Link>
        </p>
        {/* <h2>Using App Router</h2>
        <p>
          <Link href="card-deck/">Card Deck</Link>
        </p> */}
      </Layout>
    </>
  );
}
