import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "../utils/Providers";

const inter = Inter({ subsets: ["latin"] });

// TODO: put pwa metadata here?
export const metadata: Metadata = {
  title: "Payload-in-NextJs app",
  description: "Generated by create next app and next-payload",
};

type RootLayoutProps = {
  // todo: is this right type for children?
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
